const features = [
  ['◎','Always-on monitoring','GhostOps watches connected business systems continuously and surfaces changes that deserve attention.'],
  ['↗','Growth intelligence','Detect sales drops, margin pressure and operational anomalies, then turn them into clear recommendations.'],
  ['$','Recovery hunter','Find duplicate charges, missing refunds, forgotten subscriptions and other recoverable losses.'],
  ['✓','Human approval','Sensitive actions stop at Approval Center. You stay in control before GhostOps executes.'],
  ['◈','Evidence first','Every case includes the reason, supporting evidence, estimated impact and confidence before action.'],
  ['⚡','Efficient AI routing','Rules and analytics handle routine monitoring; AI reasoning is invoked only when judgment adds value.']
];

export default function Home(){return <>
  <header className="shell nav"><div className="brand"><div className="mark">G</div><span>GhostOps AI</span></div><nav className="links"><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#security">Security</a></nav><a className="btn" href="#platform">Enter Command Center</a></header>
  <main>
    <section className="shell hero"><div className="pill">● AUTONOMOUS BUSINESS OPERATIONS</div><div className="agent" aria-label="GhostOps agent"><div className="eyes"><i className="eye"/><i className="eye"/></div><b className="g">G</b></div><h1>Your business has a new <span className="grad">invisible operator.</span></h1><p>GhostOps connects to the tools that run your online business, watches what humans miss, finds recoverable losses, explains performance shifts and prepares the next best action — while you stay in control.</p><div className="actions"><a className="btn" href="#platform">Explore GhostOps</a><a className="btn secondary" href="#workflow">See how it works</a></div></section>
    <section className="shell grid" id="workflow">{features.map(([i,h,p])=><article className="card" key={h}><div className="icon">{i}</div><h3>{h}</h3><p>{p}</p></article>)}</section>
    <section className="shell section" id="platform"><h2>One command center. <span className="grad">No blind spots.</span></h2><p>A production-oriented control surface for alerts, recommendations, recovery cases, approvals and the agent activity trail.</p><div className="dashboard"><aside className="side"><div className="brand"><div className="mark">G</div><span>GhostOps</span></div><div className="menu active">◫ Overview</div><div className="menu">⚡ Intelligence</div><div className="menu">$ Recovery Cases</div><div className="menu">✓ Approval Center</div><div className="menu">◎ Connections</div><div className="menu">≡ Activity Log</div></aside><div className="main"><div className="top"><div><small style={{color:'#8490a7'}}>COMMAND CENTER</small><h2 style={{fontSize:28,marginTop:5}}>Good morning.</h2></div><span className="live">● Agent online</span></div><div className="metrics"><div className="metric"><small>Business health</small><strong>92</strong></div><div className="metric"><small>Potential recovery</small><strong>$2,840</strong></div><div className="metric"><small>Open insights</small><strong>7</strong></div></div><h3>Priority intelligence</h3><div className="alert"><div><span className="tag">RECOVERY · HIGH CONFIDENCE</span><strong style={{display:'block',marginTop:6}}>Possible duplicate platform charge</strong><p>Evidence package prepared. Estimated recoverable value: $640.</p></div><button className="btn">Review case</button></div><div className="alert"><div><span className="tag">GROWTH SIGNAL</span><strong style={{display:'block',marginTop:6}}>Conversion declined 11% over 3 days</strong><p>GhostOps isolated two products driving most of the change and prepared an experiment.</p></div><button className="btn secondary">View analysis</button></div><div className="alert"><div><span className="tag">OPERATIONAL</span><strong style={{display:'block',marginTop:6}}>Inventory risk detected</strong><p>Projected stockout in 9 days based on current velocity.</p></div><button className="btn secondary">Review</button></div></div></div></section>
    <section className="shell section" id="security"><h2>Connected by permission. <span className="grad">Controlled by you.</span></h2><p>GhostOps is designed around official OAuth/API connections, least-privilege access, server-side secrets, explicit approval for sensitive actions and a permanent audit trail. No password sharing.</p></section>
  </main><footer className="shell footer">© 2026 GhostOps AI · Autonomous Business Operations</footer>
</>}
